apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workerscriptversions.cf.guber.proc.io
spec:
  group: cf.guber.proc.io
  scope: Cluster
  names:
    plural: workerscriptversions
    singular: workerscriptversion
    kind: WorkerScriptVersion
    shortNames:
      - wsv
      - version
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["scriptName"]
              properties:
                scriptName:
                  type: string
                  description: The name of the Worker script to create a version for.
                script:
                  type: string
                  description: The JavaScript/TypeScript code for the Worker version.
                scriptUrl:
                  type: string
                  description: URL to fetch the Worker script from (alternative to inline script).
                bindings:
                  type: object
                  description: Environment bindings for the Worker version (KV, D1, etc.).
                  properties:
                    d1_databases:
                      type: array
                      items:
                        type: object
                        properties:
                          binding:
                            type: string
                            description: The binding name to use in the Worker code.
                          database_name:
                            type: string
                            description: The name of the D1 resource to bind.
                      description: D1 database bindings.
                    queues:
                      type: array
                      items:
                        type: object
                        properties:
                          binding:
                            type: string
                            description: The binding name to use in the Worker code.
                          queue_name:
                            type: string
                            description: The name of the Queue resource to bind.
                      description: Queue bindings.
                compatibility_date:
                  type: string
                  description: Compatibility date for the Worker runtime.
                compatibility_flags:
                  type: array
                  items:
                    type: string
                  description: Compatibility flags for the Worker runtime.
                annotations:
                  type: object
                  description: Annotations for the Worker version.
                  properties:
                    alias:
                      type: string
                      description: Alias for this version.
                    message:
                      type: string
                      description: Message describing this version.
                    tag:
                      type: string
                      description: Tag for this version.
                dependencies:
                  type: array
                  items:
                    type: object
                    properties:
                      kind:
                        type: string
                        description: The kind of resource this version depends on (D1, Queue, Worker, etc.).
                      name:
                        type: string
                        description: The name of the resource this version depends on.
                      group:
                        type: string
                        description: The API group of the resource (defaults to cf.guber.proc.io).
                        default: "cf.guber.proc.io"
                  description: Resources that must be ready before this version can be created.
            status:
              type: object
              properties:
                state:
                  type: string
                  description: Current provisioning state (Creating, Ready, Failed, Deleting).
                version_id:
                  type: string
                  description: Cloudflare-assigned identifier for the Worker version.
                version_number:
                  type: string
                  description: Version number assigned by Cloudflare.
                createdAt:
                  type: string
                  format: date-time
                  description: Timestamp of creation in Cloudflare.
                endpoint:
                  type: string
                  description: API endpoint for this version.
                metadata:
                  type: object
                  description: Metadata returned by Cloudflare for this version.
